[package]
name = "leash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = "0.16.20"
serde = "1.0.185"
serde_derive = "1.0.185"
toml = "0.7.6"
